---
# tasks file for sparkslave

# Assumes the MapR repos are already configured.

- name: install mapr-spark for RedHat/CentOS
  yum: name='{{item}}-{{spark_version}}.{{spark_build}}' state=present
  with_items:
    - mapr-spark
  when: ansible_distribution in ("CentOS", "RedHat", "Amazon")

- name: install mapr-spark for Debian/Ubuntu
  apt: name='{{item}}-{{spark_version}}.{{spark_build}}' state=present
  with_items:
    - mapr-spark
  when: ansible_distribution in ("Debian", "Ubuntu")

